# NUMPY

1. Numpy stand for "numerical python"
2. fundamental python package for scientific computing
3. tools and technique to solve mathematicals problems


# history 

1. in 2005 it is created by jim hugunin and other contributors

 # Numpy 
 
 1. arrays
 2. linear algebra
 3. random number generation 
 4. brodcasting
 

# array


### similarities bw list and array
1. list amd array both are use for storing data
2. both are mutable
3. list and array are indexed
4. both cab be slice

### difference b/w list and array
1. list is built in function but array is not built in function 
2. list contain all types of data but array contain the only similar kind of data
3. list can not perform the mathematical operation but array can perform


In [2]:
# list can not perform the mathematical operation but array can perform

mylist=[1,2,3,4,5]
a=mylist/3
print(a)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [3]:
# array can perform the mathemetcal operation

import numpy as np
a=np.array([1,2,3,4,5])
b=a/2
print(b)

[0.5 1.  1.5 2.  2.5]


# advantage
1. it consume less memory 
2. more convenient to use when want to do mathematical ooperations

# creating array in python numpy
there are different function to create nnumpy array
1. array ()
2. arange()
3. zero()
4. ones()
5. linspace()
6. eye()
7. random()


In [5]:
import numpy
help(numpy.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

# array()


In [3]:
import numpy as np
a=np.array([[1,2],[2,3]])
print(a)

[[1 2]
 [2 3]]


In [5]:
np.array([1,2,3,4],"complex")

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [4]:
# adding some number in array

import numpy as np
a=np.array([1,2,3,4,5])
add=a+2
print(add)

[3 4 5 6 7]


# arrange()
arange(...)<br>
    arange([start,] stop[, step,], dtype=None)

In [9]:
import numpy
help(numpy.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [12]:
import numpy as vishu
a=vishu.arange(1,5)
print(a)
print(type(a)) # it returns ndarray

[1 2 3 4]
<class 'numpy.ndarray'>


In [14]:
# we can also steping the array
import numpy as np
arr=np.arange(2,10,2) # print excluding 10 
print(arr)

[2 4 6 8]


In [3]:
# we can also pass the single value as argument which is concidered as stop value
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# we can also pass the floating values
import numpy as np
arr=np.arange(1.5,5.5)
print(arr)

[1.5 2.5 3.5 4.5]


In [1]:
# we can also pass the floating value in the steping
import numpy as np
arr=np.arange(1.5,5,0.5)
print(arr)

[1.5 2.  2.5 3.  3.5 4.  4.5]


In [4]:
# we can also pass the data-type (dtype)
np.arange(1,10,dtype="complex")

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
       9.+0.j])

In [6]:
a=np.arange(1,5,2)
print(a) # when we add print statement then it donot ret

[1 3]


In [7]:
a

array([1, 3])

## find the 9th term from end of the ap series (5,9,13,.....185)

#### solution

In [6]:
import numpy as np 

a=float(input("enter the first term: "))
l=float(input("enter the last term: "))
d=float(input("enter common defference: "))

# operation

ap=np.arange(a,l,d)

#dictionry for asking the output

dic={
    1:"print ap",
    2:"print nth item from start",
    3:"print nth item from last"
    }

print(dic)
user_key=int(input("enter the above key for want to specific operation: "))
dic.get(user_key,"nothing")


if user_key==1:
    print(ap)
elif user_key==2:
    ask=int(input("enter the nth term from start: "))
    print(ap[ask])
elif user_key==3:
    ask1=int(input("enter the nth term from last: "))
    print(ap[-(ask1-1)])
else:
    print("wrong entry")

enter the first term: 1
enter the last term: 100
enter common defference: 2
{1: 'print ap', 2: 'print nth item from start', 3: 'print nth item from last'}
enter the above key for want to specific operation: 1
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49. 51. 53. 55. 57. 59. 61. 63. 65. 67. 69. 71.
 73. 75. 77. 79. 81. 83. 85. 87. 89. 91. 93. 95. 97. 99.]
