# attributes of array in numpy


1. ndim
2. shape
3. size
4. dtype
5. itemsize

# --------------------------------------------------------------------------------------------------------------

1.ndim
--------
    returns the diamension of the arrays 
    syntax:-
    array.ndim
    

In [3]:
import numpy as np
array=np.array([1,2,3,4,5])
array.ndim

1

In [5]:
print(np.array([[12,23],[2,3]]).ndim)

2


# -------------------------------------------------------------------------------------------------------------

2.shape
---------
    return the shape of the array in (row,column)
    syntax:-
    array.shape

In [8]:
array=np.array([1,4,3,34,5,5])
array.shape

(6,)

In [12]:
array=np.array([[2,3,4,5,6],[3,4,5,3]])
array.shape

(2,)

In [13]:
array=np.array([[2,3,4,5,6],[3,4,5,3,4]])
array.shape

(2, 5)

In [22]:
print(np.zeros([2,3,4])) 
print("\n\n\n",np.zeros([2,3,4]).shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]



 (2, 3, 4)


# --------------------------------------------------------------------------------------------------------------

3.size
--------
     >return the size of the arrays
     >the total number of items in the array
      syntax
      array.size
      

In [23]:
print(np.array([1,2,3,34,4,5]).size)

6


In [26]:
print(np.array([[1,2,3,34,4,5],[23,4,45,3,3,34]]).size)

12


In [27]:
# if 

print(np.array([[1,2,3,34,4,5],[23,4,45,3,3]]).size)

2


In [29]:
print(np.ones([2,3,4]).size)

24


# --------------------------------------------------------------------------------------------------------------

4.dtype
------
     RETURN THE DATA TYPE OF THE ARRAY
     
     SYNTAX
     array.dtype

In [31]:
a=np.array([2,3,4])
print(a.dtype)

int32


In [34]:
print(np.ones([2,3]).dtype)

float64


In [38]:
print(np.zeros(3).dtype)

float64


# --------------------------------------------------------------------------------------------------------------

5.itemsize
--------

    RETURN THE SIZE OF THE ARRAY IN BITS
    
    SYNTAX
    array.itemsize

In [41]:
a=np.array([2,3,4,5,5,6,7])
print(a.itemsize,"bits")

4 bits
