# linspace()

this linspace () and arange() function is evenly same,   here we menstion the space
> linspace(start,end,num=50,endpoint=True,)

In [1]:
# iska use ham arithimetic progration me use kar sakte hai
import numpy as np
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [4]:
np.linspace(2,20) # here start and stop value is maneratry and if num is not pass then it concidered 50 by defualt

array([ 2.        ,  2.36734694,  2.73469388,  3.10204082,  3.46938776,
        3.83673469,  4.20408163,  4.57142857,  4.93877551,  5.30612245,
        5.67346939,  6.04081633,  6.40816327,  6.7755102 ,  7.14285714,
        7.51020408,  7.87755102,  8.24489796,  8.6122449 ,  8.97959184,
        9.34693878,  9.71428571, 10.08163265, 10.44897959, 10.81632653,
       11.18367347, 11.55102041, 11.91836735, 12.28571429, 12.65306122,
       13.02040816, 13.3877551 , 13.75510204, 14.12244898, 14.48979592,
       14.85714286, 15.2244898 , 15.59183673, 15.95918367, 16.32653061,
       16.69387755, 17.06122449, 17.42857143, 17.79591837, 18.16326531,
       18.53061224, 18.89795918, 19.26530612, 19.63265306, 20.        ])

In [3]:
import numpy as np
np.linspace(2,18,num=10) # it divide the array item in 10 interval and it returns float type by defualt 

array([ 2.        ,  3.77777778,  5.55555556,  7.33333333,  9.11111111,
       10.88888889, 12.66666667, 14.44444444, 16.22222222, 18.        ])

In [7]:
# int type return
np.linspace(2,20,num=10,dtype="int")

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
#see also

a=np.linspace(2,20,num=5,dtype="int")
b=np.linspace(2,20,num=5)
print(a)# return int type bcoz it is mensioned
print(b)# return float type by defualt

[ 2  6 11 15 20]
[ 2.   6.5 11.  15.5 20. ]


In [20]:
np.linspace(2,20,num=10,endpoint=False) # if endpoint is False then then not concidered the endpoint by default it is True

array([ 2. ,  3.8,  5.6,  7.4,  9.2, 11. , 12.8, 14.6, 16.4, 18.2])

In [21]:
np.linspace(2,20,num=10,endpoint=True) # it concidered the last point

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [7]:
#calculates the 500 number b/w 1 and 2 in one line


import numpy as np

np.linspace(1,2,num=500)

array([1.        , 1.00200401, 1.00400802, 1.00601202, 1.00801603,
       1.01002004, 1.01202405, 1.01402806, 1.01603206, 1.01803607,
       1.02004008, 1.02204409, 1.0240481 , 1.0260521 , 1.02805611,
       1.03006012, 1.03206413, 1.03406814, 1.03607214, 1.03807615,
       1.04008016, 1.04208417, 1.04408818, 1.04609218, 1.04809619,
       1.0501002 , 1.05210421, 1.05410822, 1.05611222, 1.05811623,
       1.06012024, 1.06212425, 1.06412826, 1.06613226, 1.06813627,
       1.07014028, 1.07214429, 1.0741483 , 1.0761523 , 1.07815631,
       1.08016032, 1.08216433, 1.08416834, 1.08617234, 1.08817635,
       1.09018036, 1.09218437, 1.09418838, 1.09619238, 1.09819639,
       1.1002004 , 1.10220441, 1.10420842, 1.10621242, 1.10821643,
       1.11022044, 1.11222445, 1.11422846, 1.11623246, 1.11823647,
       1.12024048, 1.12224449, 1.1242485 , 1.12625251, 1.12825651,
       1.13026052, 1.13226453, 1.13426854, 1.13627255, 1.13827655,
       1.14028056, 1.14228457, 1.14428858, 1.14629259, 1.14829

In [8]:
# here we return the difference between two step (retstep=True)


np.linspace(1,2,num=500,retstep=True)

(array([1.        , 1.00200401, 1.00400802, 1.00601202, 1.00801603,
        1.01002004, 1.01202405, 1.01402806, 1.01603206, 1.01803607,
        1.02004008, 1.02204409, 1.0240481 , 1.0260521 , 1.02805611,
        1.03006012, 1.03206413, 1.03406814, 1.03607214, 1.03807615,
        1.04008016, 1.04208417, 1.04408818, 1.04609218, 1.04809619,
        1.0501002 , 1.05210421, 1.05410822, 1.05611222, 1.05811623,
        1.06012024, 1.06212425, 1.06412826, 1.06613226, 1.06813627,
        1.07014028, 1.07214429, 1.0741483 , 1.0761523 , 1.07815631,
        1.08016032, 1.08216433, 1.08416834, 1.08617234, 1.08817635,
        1.09018036, 1.09218437, 1.09418838, 1.09619238, 1.09819639,
        1.1002004 , 1.10220441, 1.10420842, 1.10621242, 1.10821643,
        1.11022044, 1.11222445, 1.11422846, 1.11623246, 1.11823647,
        1.12024048, 1.12224449, 1.1242485 , 1.12625251, 1.12825651,
        1.13026052, 1.13226453, 1.13426854, 1.13627255, 1.13827655,
        1.14028056, 1.14228457, 1.14428858, 1.14