# zeros() function


In [4]:
<div class="burk">
import <span class="burk"><span class="mark"><span class="burk">numpy as np
he</span></span></span>lp(np.zeros)</div><i class="fa fa-lightbulb-o "></i>

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [5]:
# one dimensional zeros array
import numpy as np
a=np.zeros(5)
print("by default returns float types",a)

by default returns float types [0. 0. 0. 0. 0.]


In [6]:
# two dimensional array integer type
import numpy as np
np.zeros(5,dtype="int")

array([0, 0, 0, 0, 0])

In [3]:
import numpy as np
np.zeros((2,3)) # note is take tuple or list for creating ndarray here row=2 and column=3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
a=np.zeros([3,4], dtype="int") # takes list also row=3 and column=4
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [1]:
import numpy as n
help(n.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [1]:
import numpy as n
n.ones((2,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1]])

In [2]:
n.ones(2,dtype="int")

array([1, 1])

In [3]:
n.ones(3)

array([1., 1., 1.])

In [4]:
# we can also pass the list in the shape of the ones function as argument
n.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [1]:
import numpy as n
help(n.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

In [4]:
# empty() ones() and zeros() all are the similar function in numpy but it returns deffrent values
import numpy as n
n.empty(2,dtype="int")
# empty returns the random number

array([107152392,       371])

In [8]:
import numpy as np
np.empty([3,4],dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
import numpy as np
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [2]:
import numpy as np
np.zeros((2,3,3),dtype="int")

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])